DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

QTYY/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from homePart.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('commuityPart/', include('commuityPart.urls')),
    path('contactPart/', include('contactPart.urls')),
    path('newsPart/', include('newsPart.urls')),
    path('videoPart/', include('videoPart.urls')),
    path('aboutPart/', include('aboutPart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

aboutPart/urls.py
from django.urls import path
from . import views

app_name = 'aboutPart'  # 设置应用名

urlpatterns = [
    path('products/<str:productName>/', views.products, name='products'),#产品列表
    path('productDetail/<int:id>/', views.productDetail, name='productDetail'),#产品详情
]

aboutPart/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
 
class Product(models.Model):
    PRODUCTS_CHOICES = (
        ('足球装备', '足球装备'),
        ('周边商品', '周边商品'),
       
        
    )
    title = models.CharField(max_length=50, verbose_name=' 产品标题')
    description = models.TextField(verbose_name='产品详情描述')
    productType = models.CharField(choices=PRODUCTS_CHOICES,
                                   max_length=50,
                                   verbose_name='产品类型')
    price = models.DecimalField(max_digits=7,
                                decimal_places=1,
                                blank=True,
                                null=True,
                                verbose_name='产品价格')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='发布时间')
    views = models.PositiveIntegerField('浏览量', default=0)
 
    def __str__(self):
        return self.title
 
    class Meta:
        verbose_name = '产品'
        verbose_name_plural = '产品'
        ordering = ('-publishDate', )

class ProductImg(models.Model):
    product = models.ForeignKey(Product,
                                related_name='productImgs',
                                verbose_name='产品',
                                on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='Product/',
                              blank=True,
                              verbose_name='产品图片')
 
    class Meta:
        verbose_name = '产品图片'
        verbose_name_plural = '产品图片'

aboutPart/views.py
# Create your views here.


# def about(request):
#     return render(request, 'about.html')

from django.shortcuts import render
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from .models import Product

# Create your views here.
def products(request, productName):
    submenu = productName
    if productName == 'robot':
        productName = '足球装备'
    elif productName == 'monitor':
        productName = '周边商品'
    # else:
    #     productName = '人脸识别解决方案'

    productList = Product.objects.all().filter(
        productType=productName).order_by('-publishDate')

    p = Paginator(productList, 2)
    if p.num_pages <= 1:
        pageData = ''
    else:
        page = int(request.GET.get('page', 1))
        productList = p.page(page)
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:
            right = page_range[page:page + 2]
            print(total_pages)
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            right = page_range[page:page + 2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        pageData = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }

    return render(
        request, 'productList.html', {
            'active_menu': 'products',
            'sub_menu': submenu,
            'productName': productName,
            'productList': productList,
            'pageData': pageData,
        })

def productDetail(request, id):
    product = get_object_or_404(Product, id=id)
    product.views += 1
    product.save()
    return render(request, 'productDetail.html', {
        'active_menu': 'products',
        'product': product,
    })

aboutPart/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}
关于我们
{% endblock %}

{% block content %}

{% endblock %}

aboutPart/templates/productDetail.html
{% extends "base.html" %}
{% load static %}
 
{% block title %}
产品详情
{% endblock %}
 
{% block content %}
<link href="{% static 'css/products.css' %}" rel="stylesheet">
<!-- 主体内容 -->
<div class="container">
    <div class="model-details-product-title">
        {{product.title}}
    </div>
    <div class="model-details">
        {% for img in product.productImgs.all %}
        <div class="row-4">
            <img class="img-responsive" src="{{img.photo.url}}">
        </div>
        {% endfor %}
        <h3>产品介绍</h3>
        <p>
            {{product.description|linebreaks}}
        </p>
        <h3>参考价格</h3>
        <p>
            {{product.price}}元
        </p>
    </div>
</div>
{% endblock %}

aboutPart/templates/productList.html
{% extends "base.html" %}
{% load static %}

{% block title %}
商城
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/li.css' %}">
<div class="line"></div>
<!-- 广告横幅 -->
<div class="container-fluid">
    <div class="row">
        <img class="img-responsive model-img" 
src="{% static 'assets/images/products.jpg' %}">
    </div>
</div>
<!-- 主体内容 -->
<div class="container">
    <div class="row row-3">
        <!-- 侧边导航栏 -->
        <div class="col-md-3">
            <div class="model-title">
                商城
            </div>
            <div class="model-list">
                <ul class="list-group">
                    <li class="list-group-item" id="robot">
                        <a href="{% url 'aboutPart:products' 'robot' %}">足球装备</a>
                    </li>
                    <li class="list-group-item" id="monitor">
                        <a href="{% url 'aboutPart:products' 'monitor' %}">周边商品</a>
                    </li>
                    <!-- <li class="list-group-item" id="face">
                        <a href="{% url 'aboutPart:products' 'face' %}">
                            </a>
                    </li> -->
                </ul>
            </div>
        </div>
        <!-- 说明文字和图片 -->
        <div class="col-md-9">
            <div class="model-details-title">
                {{productName}}
            </div>
            <!-- 此处填入产品列表内容 -->
            <div class="model-details">
                {% for product in productList %}
<div class="row">
    <div class="col-md-6">
        {% for img in product.productImgs.all %}
            {% if forloop.first %}
            <a href="{% url 'aboutPart:productDetail' product.id %}" class="thumbnail row-4">
                <img class="img-responsive model-img" src="{{img.photo.url}}">
            </a>
            {% endif %}
        {% endfor %}
    </div>
    <div class="col-md-6">
        <h3>{{ product.title|truncatechars:"20" }}</h3>
        <p>{{ product.description|truncatechars:"150"|linebreaks }}</p>
        <div class="thumbnail row-5">
            <div class="caption">
                <a href="{% url 'aboutPart:productDetail' product.id %}" class="btn btn-primary" role="button">
                    查看详情
                </a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% if pageData %}
<div class="paging">
    <ul id="pages" class="pagination pagination-sm pagination-xs">
        {% if pageData.first %}
        <li><a href="?page=1">1</a></li>
        {% endif %}
        {% if pageData.left %}
        {% if pageData.left_has_more %}
        <li><span>...</span></li>
        {% endif %}
        {% for i in pageData.left %}
        <li><a href="?page={{i}}">{{i}}</a></li>
        {% endfor %}
        {% endif %}
        <li class="active"><a href="?page={{pageData.page}}">{{pageData.page}}</a></li>
        {% if pageData.right %}
        {% for i in pageData.right %}
        <li><a href="?page={{i}}">{{i}}</a></li>
        {% endfor %}
        {% if pageData.right_has_more %}
        <li><span>...</span></li>
        {% endif %}
        {% endif %}
        {% if pageData.last %}
        <li><a href="?page={{pageData.total_pages}}">{{pageData.total_pages}}</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}


{% endblock %}