DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

QTYY/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from homePart.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('commuityPart/', include('commuityPart.urls')),
    path('contactPart/', include('contactPart.urls')),
    path('newsPart/', include('newsPart.urls')),
    path('videoPart/', include('videoPart.urls')),
    path('aboutPart/', include('aboutPart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

aboutPart/urls.py
from django.urls import path
from . import views

app_name = 'aboutPart'  # 设置应用名

urlpatterns = [
    path('products/<str:productName>/', views.products, name='products'),#产品列表
    path('productDetail/<int:id>/', views.productDetail, name='productDetail'),#产品详情
]

contactPart/urls.py
from django.urls import path
from . import views

app_name = 'contactPart'  # 设置应用名

urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

newsPart/urls.py
from django.urls import path
from . import views

app_name = 'newsPart'  # 设置应用名

urlpatterns = [
    path('news/', views.news, name='news'),
]

videoPart/urls.py
from django.urls import path
from . import views

app_name = 'videoPart'  # 设置应用名

urlpatterns = [
    path('video/', views.video, name='video'),
]

templates/base.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
    <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <title>QTYY|{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="{% static 'assets/favicon.ico' %}">

        <!--Google Font link-->
        <link
            href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">


        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/slick/slick-theme.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/iconfont.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/bootsnav.css' %}">

        <!-- xsslider slider css -->


        <!--<link rel="stylesheet" href="assets/css/xsslider.css">-->




        <!--For Plugins external css-->
        <!--<link rel="stylesheet" href="assets/css/plugins.css" />-->

        <!--Theme custom css -->
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <!--<link rel="stylesheet" href="assets/css/colors/maron.css">-->

        <!--Theme Responsive css-->
        <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />

        <script src="{% static 'assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>

    <body data-spy="scroll" data-target=".navbar-collapse">


        <!-- Preloader -->

        <!--End off Preloader -->


        <div class="culmn">
            <!--Home page style-->


            <nav class="navbar navbar-default bootsnav navbar-fixed">
                <div class="navbar-top bg-grey fix">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="navbar-callus text-left sm-text-center">
                                    <ul class="list-inline">
                                        <li><a href=""><i class="fa fa-envelope-o"></i> Contact us: your@email.com</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="navbar-socail text-right sm-text-center">
                                    <ul class="list-inline">
                                        <li><a href=""><i class="fa fa-dribbble"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Start Top Search -->
                <div class="top-search">
                    <div class="container">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            <input type="text" class="form-control" placeholder="Search">
                            <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
                        </div>
                    </div>
                </div>
                <!-- End Top Search -->


                <div class="container">
                    <div class="attr-nav">
                        <ul>
                            <li class="search"><a href="#"><i class="fa fa-search"></i></a></li>
                        </ul>
                    </div>

                    <!-- Start Header Navigation -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="#brand">
                            <img src="assets/images/logo.png" class="logo" alt="">
                            <!--<img src="assets/images/footer-logo.png" class="logo logo-scrolled" alt="">-->
                        </a>

                    </div>
                    <!-- End Header Navigation -->

                    <!-- navbar menu -->
                    <div class="collapse navbar-collapse" id="navbar-menu">
                        
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'home' %}">首页</a></li>
                            <li class="dropdown nav-top" id='products'>
                                <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                                    商城</a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'aboutPart:products' 'robot' %}">
                                            足球装备</a></li>
                                    <li><a href="{% url 'aboutPart:products' 'monitor' %}">
                                            周边商品</a></li>
                                    <!-- <li><a href="{% url 'aboutPart:products' 'face' %}">
                                            人脸识别解决方案</a></li> -->
                                </ul>
                            </li>

                            
                            
                            <li><a href="{% url 'newsPart:news' %}">团队动态</a></li>
                            <li><a href="{% url 'commuityPart:commuity' %}">社区</a></li>
                            <li><a href="{% url 'videoPart:video' %}">视频课程</a></li>
                            <li><a href="{% url 'contactPart:contact' %}">联系我们</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div>
            </nav>
        </div>
        {% block content %}
        {% endblock %}
        <!-- JS includes -->
        <script src="{% static 'assets/js/vendor/jquery-1.11.2.min.js'%}"></script>
        <script src="{% static 'assets/js/vendor/bootstrap.min.js'%}"></script>
        <script src="{% static 'assets/js/owl.carousel.min.js'%}"></script>
        <script src="{% static 'assets/js/jquery.magnific-popup.js'%}"></script>
        <script src="{% static 'assets/js/jquery.easing.1.3.js'%}"></script>
        <script src="{% static 'assets/css/slick/slick.js'%}"></script>
        <script src="{% static 'assets/css/slick/slick.min.js'%}"></script>
        <script src="{% static 'assets/js/jquery.collapse.js'%}"></script>
        <script src="{% static 'assets/js/bootsnav.js'%}"></script>
        <script src="{% static 'assets/js/plugins.js'%}"></script>
        <script src="{% static 'assets/js/main.js'%}"></script>
    </body>

</html>

templates/biaobase.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
    <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <title>QTYY|{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="{% static 'assets/favicon.ico' %}">

        <!--Google Font link-->
        <link
            href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">


        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/slick/slick-theme.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/iconfont.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/bootsnav.css' %}">
        <style>
            .navbar {
                width: 100%;
            }
        </style>
        <script src="{% static 'assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

        <!-- xsslider slider css -->


        <!--<link rel="stylesheet" href="assets/css/xsslider.css">-->




        <!--For Plugins external css-->
        <!--<link rel="stylesheet" href="assets/css/plugins.css" />-->

        <!--Theme custom css -->
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <!--<link rel="stylesheet" href="assets/css/colors/maron.css">-->

        <!--Theme Responsive css-->
        <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />

        <script src="{% static 'assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>

    <body data-spy="scroll" data-target=".navbar-collapse">


        <!-- Preloader -->

        <!--End off Preloader -->


        <div class="culmn">
            <!--Home page style-->


            <nav class="navbar navbar-default bootsnav navbar-fixed">
                <div class="navbar-top bg-grey fix">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="navbar-callus text-left sm-text-center">
                                    <ul class="list-inline">
                                        <li><a href=""><i class="fa fa-envelope-o"></i> Contact us: your@email.com</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="navbar-socail text-right sm-text-center">
                                    <ul class="list-inline">
                                        <li><a href=""><i class="fa fa-dribbble"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Start Top Search -->
                <div class="top-search">
                    <div class="container">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            <input type="text" class="form-control" placeholder="Search">
                            <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
                        </div>
                    </div>
                </div>
                <!-- End Top Search -->


                <div class="container">
                    <div class="attr-nav">
                        <ul>
                            <li class="search"><a href="#"><i class="fa fa-search"></i></a></li>
                        </ul>
                    </div>

                    <!-- Start Header Navigation -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="#brand">
                            <img src="#" class="logo" alt="">
                            <!--<img src="assets/images/footer-logo.png" class="logo logo-scrolled" alt="">-->
                        </a>

                    </div>
                    <!-- End Header Navigation -->

                    <!-- navbar menu -->
                    <div class="collapse navbar-collapse" id="navbar-menu" style="overflow: hidden">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'home' %}">首页</a></li>
                            <li><a href="{% url 'aboutPart:about' %}">关于我们</a></li>
                            <li class="dropdown nav-top" id='news'>
                                <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                                    团队动态</a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'newsPart:news' 'com_new' %}">管理团队</a></li>
                                    <li><a href="{% url 'newsPart:news' 'spe_new' %}">师资团队</a></li>
                                    <li><a href="{% url 'newsPart:news' 'man_new' %}">课程研发团队</a></li>
                                </ul>
                            </li>
                            <li class="dropdown nav-top" id='community'>
                                <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                                    社区</a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'communityPart:community' 'knowledge' %}">足球新闻&小知识</a></li>
                                    <li><a href="{% url 'communityPart:community' 'English' %}">足球英语</a></li>
                                    <li><a href="{% url 'communityPart:community' 'policy' %}">体育相关政策</a></li>
                                    <li><a href="{% url 'communityPart:community' 'health' %}">健康知识</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'videoPart:video' 'video_skill' %}">视频课程</a></li>
                            <li class="dropdown nav-top" id='video'>
                                <a href="#" class="dropdown-toggle on" data-toggle="dropdown">
                                    视频课程</a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'videoPart:video' 'video_skill' %}">
                                            技术视频</a></li>
                                    <li><a href="{% url 'videoPart:video' 'video_attack' %}">
                                            战术视频</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'videoPart:video' 'video_attack' %}">商城</a></li>
                            <li><a href="{% url 'contactPart:contact' %}">联系我们</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div>
            </nav>
        </div>
        {% block content %}
        {% endblock %}
        <!-- JS includes -->
        <script src="{% static 'assets/js/vendor/jquery-1.11.2.min.js'%}"></script>
        <script src="{% static 'assets/js/vendor/bootstrap.min.js'%}"></script>
        <script src="{% static 'assets/js/owl.carousel.min.js'%}"></script>
        <script src="{% static 'assets/js/jquery.magnific-popup.js'%}"></script>
        <script src="{% static 'assets/js/jquery.easing.1.3.js'%}"></script>
        <script src="{% static 'assets/css/slick/slick.js'%}"></script>
        <script src="{% static 'assets/css/slick/slick.min.js'%}"></script>
        <script src="{% static 'assets/js/jquery.collapse.js'%}"></script>
        <script src="{% static 'assets/js/bootsnav.js'%}"></script>
        <script src="{% static 'assets/js/plugins.js'%}"></script>
        <script src="{% static 'assets/js/main.js'%}"></script>
    </body>

</html>