DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

QTYY/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from homePart.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('commuityPart/', include('commuityPart.urls')),
    path('contactPart/', include('contactPart.urls')),
    path('newsPart/', include('newsPart.urls')),
    path('videoPart/', include('videoPart.urls')),
    path('aboutPart/', include('aboutPart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

communityPart/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

app_name = 'communityPart'  # 设置应用名

urlpatterns = [
    path('community/<str:communityName>/', views.community, name='community'),#社区列表
    path('communityDetail/<int:id>/', views.communityDetail, name='communityDetail'),#社区详情
]

communityPart/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Community(models.Model):
    COMMUNITY_CHOICES = (
        ('足球新闻&小知识', '足球新闻&小知识'),
        ('足球英语', '足球英语'),
        ('体育相关政策', '体育相关政策'),
        ('健康知识','健康知识')
    )
    title = models.CharField(max_length=50, verbose_name=' 社区标题')
    description = models.TextField(verbose_name='社区详情描述')
    communityType = models.CharField(choices=COMMUNITY_CHOICES,
                                   max_length=50,
                                   verbose_name='社区类型')
    price = models.DecimalField(max_digits=7,
                                decimal_places=1,
                                blank=True,
                                null=True,
                                verbose_name='社区发布量')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='发布时间')
    views = models.PositiveIntegerField('浏览量', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '社区'
        verbose_name_plural = '社区'
        ordering = ('-publishDate', )


class CommunityImg(models.Model):
    community = models.ForeignKey(Community,
                                related_name='communityImgs',
                                verbose_name='社区',
                                on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='Community/',
                              blank=True,
                              verbose_name='社区图片')

    class Meta:
        verbose_name = '社区图片'
        verbose_name_plural = '社区图片'

communityPart/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from .models import Community
# Create your views here.
# 创建视图处理函数

def community(request, communityName):
    submenu = communityName
    if communityName == 'knowledge':
        communityName = '足球新闻&小知识'
    elif communityName == 'English':
        communityName = '足球英语'
    elif communityName == 'policy':
        communityName = '体育相关政策'
    else:
        communityName = '健康知识' 

    communityList=Community.objects.all().filter(
        communityType=communityName).order_by('-publishDate')

    p = Paginator(communityList, 2)
    if p.num_pages <= 1:
        pageData = ''
    else:
        page = int(request.GET.get('page', 1))
        communityList = p.page(page)
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:
            right = page_range[page:page + 2]
            print(total_pages)
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            right = page_range[page:page + 2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        pageData = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }


    return render(
        request,'communityList.html',{
            'active_menu':'community',
            'sub_menu':submenu,
            'communityName':communityName,
            'communityList':communityList,
            'pageDate':pageData,
        })

def communityDetail(request, id):
    community = get_object_or_404(community, id=id)
    community.views += 1
    community.save()
    return render(request, 'communityDetail.html', {
        'active_menu': 'community',
        'community': community,
    })

communityPart/templates/communityDetail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
社区详情
{% endblock %}

{% block content %}
<link href="{% static '/assets/css/community.css' %}" rel="stylesheet">
<!-- 主体内容 -->
<div class="container">
    <div class="model-details-community-title">
        {{community.title}}
    </div>
    <div class="model-details">
        {% for img in community.communityImgs.all %}
        <div class="row-4">
            <img class="img-responsive" src="{{img.photo.url}}">
        </div>
        {% endfor %}
        <h3>社区介绍</h3>
        <p>
            {{community.description|linebreaks}}
        </p>
        <h3>参考价格</h3>
        <p>
            {{community.price}}元
        </p>
    </div>
</div>
{% endblock %}

communityPart/templates/communityList.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{communityName}}
{% endblock %}

{% block content %}
<link href="{% static 'assets/css/community.css' %}" rel="stylesheet">
<!-- 广告横幅 -->
<div class="container-fluid">
    <div class="row"
        style='text-align: center; width: 1500px; border: green solid 1px;max-width: 100%; margin-top:100px'>
        <img class="img-responsive model-img" src="{% static 'assets/images/community-1.png' %}"
            style="margin: 0 auto;">
    </div>
</div>
<!-- 主体内容 -->
<div class="container">
    <div class="row row-3">
        <!-- 侧边导航栏 -->
        <div class="col-md-3">
            <div class="model-title"
                style="text-align: center;background-color:#005197;color:#FFF;font-size:28px;margin-top:20px;padding:10px">
                社区
            </div>
            <div class="model-list">
                <ul class="list-group">
                    <li class="list-group-item" id="knowlegde">
                        <a href="{% url 'communityPart:community' 'knowlegde' %}">足球新闻&小知识</a>
                    </li>
                    <li class="list-group-item" id="English">
                        <a href="{% url 'communityPart:community' 'English' %}">足球英语</a>
                    </li>
                    <li class="list-group-item" id="policy">
                        <a href="{% url 'communityPart:community' 'policy' %}">体育相关政策</a>
                    </li>
                    <li class="list-group-item" id="health">
                        <a href="{% url 'communityPart:community' 'health' %}">健康知识</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- 说明文字和图片 -->
        <div class="col-md-9">
            <div class="model-details-title">
                {{communityName}}
            </div>
            <hr />
            <!-- 此处填入社区列表内容 -->
            <div class="model-details">
                {% for community in communityList %}
                <div class="row">
                    <div class="col-md-6">
                        {% for img in community.communityImgs.all %}
                        {% if forloop.first %}
                        <a href="{% url 'communityPart:communityDetail' community.id %}" class="thumbnail row-4">
                            <img class="img-responsive model-img" src="{{img.photo.url}}">
                        </a>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div class="col-md-6">
                        <h3>{{ community.title|truncatechars:"20" }}</h3>
                        <p>{{ community.description|truncatechars:"150"|linebreaks }}</p>
                        <div class="thumbnail row-5">
                            <div class="caption">
                                <a href="{% url 'communityPart:communityDetail' community.id %}" class="btn btn-primary"
                                    role="button">
                                    查看详情
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

                {% if pageData %}
                <div class="paging">
                    <ul id="pages" class="pagination pagination-sm pagination-xs">
                        {% if pageData.first %}
                        <li><a href="?page=1">1</a></li>
                        {% endif %}
                        {% if pageData.left %}
                        {% if pageData.left_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% for i in pageData.left %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{pageData.page}}">{{pageData.page}}</a></li>
                        {% if pageData.right %}
                        {% for i in pageData.right %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                        {% if pageData.right_has_more %}
                        <li><span>...</span></li>
                        {% endif %}
                        {% endif %}
                        {% if pageData.last %}
                        <li><a href="?page={{pageData.total_pages}}">{{pageData.total_pages}}</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}